apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name_application.name }}-service
spec:
  selector:
    app: {{ .Values.name_application.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.load_balancer_port.port }}
      targetPort: {{ .Values.pod_port.port }}
  type: {{ .Values.service_type.service }}
